### ISSUE TITLE
Verspätungsgründe auf Bahnhofsseite und Zugseite unterschiedlich

### ISSUE THREAD

**Issue by f2k1de** [marudor/bahn.expert#964]
**Describe the bug**
In der Bahnhofsübersicht wird bei dem Zug 16:13: verspätete Bereitstellung des Zuges angezeigt, wenn man jedoch drauf klickt ist der Grund und Zeitstempel ein ganz anderer: 16:02: Vorfahrt eines anderen Zuges.

![IMG_4969](https://github.com/user-attachments/assets/5092be83-dfbb-4f0d-a000-55204637a783)
![IMG_4971](https://github.com/user-attachments/assets/1301e8bd-4198-4ce9-9032-a1f48e2dbe25)

**Expected behavior**
Auf beiden Ansichten sind die selben Verspätungsgründe und Zeitstempel dafür. 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS
 - Browser Safari
 - Version 17.7

**Comment by lattaai1** [comment]
Hello, I've fixed this issue!

This is what I've done:
I have updated the Times component to display messages consistently between the overview and detail views. The changes ensure that both views use the same source of information for delay messages.

I also created pull request: https://github.com/marudor/bahn.expert/pull/965


> [!CAUTION]  
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

**Comment by marudor** [comment]
Ist es nicht. Auf der Detailseite siehst du den Grund für Charlottenburg. Auf der Abfahrts hast du Berlin Hbf. Da lagen halt andere Gründe vor.

**Comment by f2k1de** [comment]
Warum wird mir dann auf der Detailseite nur einer angezeigt? 
Zumal 16:02 < 16:13, aber die Vorfahrt eines anderen Zuges ja die Sache ist die mich ggf. mehr interessieren sollte weil Bereitstellung idr. früher erfolgt auch wenn der Grund später eingetragen wurde, oder?

**Comment by marudor** [comment]
Nein, Gründe hängen an Halten. => Gibts da halt nicht.
