### ISSUE TITLE
Bahn expert extrem langsam beim Daten Abruf

### ISSUE THREAD

**Issue by kiam001** [marudor/bahn.expert#970]
**Describe the bug**
Bahn expert lädt Bahnhöfe, Zug Verlaufe, und Bahnhof Haltestellen in suche extrem langsam

**To Reproduce**
Bahn expert nutzen, bahnhof eingeben, Zug auswählen.

**Expected behavior**
Extrem lange Wartezeiten weiß aber nicht ob die Bahn API so langsam ist oder Bahn expert zurzeit viel genutzt wird.

**Smartphone (please complete the following information):**
 - Device: Poco x6 5G
 - OS: Lineage 14
 - Browser Chrome
 - Version 130.0.6723.102

**Additional context**
Danke, für dein Projekt, wenn weitere Informationen benötigt werden jederzeit gerne Schreiben ich antworte in wenigen Minuten.

**Comment by lattaai3** [comment]
Hello, I tried to fix the issue

This is what I did:

Add caching to the stop place search functionality to improve performance and reduce API calls.

I also created pull request: https://github.com/marudor/bahn.expert/pull/971


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.
